### ISSUE TITLE
Example compile error

### ISSUE THREAD

**Issue by espresso0000** [senegalo/tfmini-plus#3]
exit status 1
'class TFMiniPlus' has no member named 'getSensorTempreture'

Just installed your library with the add .zip, loaded the read data example, and get this error upon compile

**Comment by senegalo** [comment]
Hello @espresso0000,

You are absolutely right ! it seems like you copied the example from the readme .. unfortunately there is a typo in the readme it is written `getSensorTempreture` while it should be `getSensorTemperature` as defined here:  https://github.com/senegalo/TFMiniPlus/blob/master/src/TFMiniPlus.h#L35

Sorry for that .. and so sorry for the delay in response ! 

Let me know if i can help you more
