### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Runsolutions** [senegalo/tfmini-plus#4]
arm-none-eabi-g++ -o .pioenvs/due/firmware.elf -T flash.ld -Os -mthumb -Wl,--gc-sections -Wl,--check-sections -Wl,--unresolved-symbols=report-all -Wl,--warn-common -Wl,--warn-section-align -mcpu=cortex-m3 -Wl,--entry=Reset_Handler -u _sbrk -u link -u _close -u _fstat -u _isatty -u _lseek -u _read -u _write -u _exit -u kill -u _getpid .pioenvs/due/src/TFMiniPlus.cpp.o -L.pioenvs/due -L/home/toni/.platformio/packages/framework-arduinosam/variants/arduino_due_x/linker_scripts/gcc -L/home/toni/.platformio/packages/framework-arduinosam/variants/arduino_due_x -Wl,--start-group .pioenvs/due/libFrameworkArduinoVariant.a .pioenvs/due/libFrameworkArduino.a -lc -lm -lsam_sam3x8e_gcc_rel -lgcc -Wl,--end-group
.pioenvs/due/libFrameworkArduino.a(main.cpp.o): In function `main':
main.cpp:(.text.startup.main+0x1a): undefined reference to `setup'
main.cpp:(.text.startup.main+0x1e): undefined reference to `loop'
collect2: error: ld returned 1 exit status
*** [.pioenvs/due/firmware.elf] Error 1

**Comment by senegalo** [comment]
Hello @Runsolutions 
So sorry for the delay in response believe it or not .. i just saw the issue !

Could you please give me more details in your main.ccp ?

it seems "shot in the dark here" that you're missing a import

let me know if i can still help you
