### ISSUE TITLE
Possible mistake in README.md

### ISSUE THREAD

**Issue by berbaba** [senegalo/tfmini-plus#7]
In the section [Change the output format](https://github.com/senegalo/TFMiniPlus/blob/master/README.md#change-the-output-format) the example uses the method `.setFrameRate(TFMINI_MEASUREMENT_MM);` but it explains that should be used `setMeasurementTo(TFMINI_MEASUREMENT_MM)`. I believe this could be a mistake from a copy/paste of the Frame rate section.

**Comment by senegalo** [comment]
Hey @berbaba i am a little bit swamped these days .. if you hand me a PR i would be More than happy to merge it.

otherwise I'll take care of it in a few weeks so no pressure.

and yes probably a copy paste mishap !

And thanks for poking me about it :)

**Comment by senegalo** [comment]
fixed in #8 thanks to @berbaba
